BUNDLE_NAME = Prefs

Prefs_FILES = RTRootVC.m
Prefs_CFLAGS = -fobjc-arc
Prefs_FRAMEWORKS = UIKit
Prefs_INSTALL_PATH = /Library/PreferenceBundles
Prefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
