BUNDLE_NAME = RespringlessPrefs

RespringlessPrefs_FILES = RTRootVC.m
RespringlessPrefs_CFLAGS = -fobjc-arc
RespringlessPrefs_FRAMEWORKS = UIKit
RespringlessPrefs_INSTALL_PATH = /Library/PreferenceBundles
RespringlessPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
